FROM openjdk:8-alpine
COPY ./antlr-4.9-complete.jar /usr/local/lib/antlr4-tool.jar
RUN addgroup -g 1000 nonroot \
    && adduser -u 1000 -G nonroot -D -H nonroot
USER 1000:1000
WORKDIR /work
COPY ./htmlapi.g4 .
ENTRYPOINT ["java", "-Xmx500M", "-cp", "/usr/local/lib/antlr4-tool.jar", "org.antlr.v4.Tool"]