//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from htmlapi.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="htmlapiParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IhtmlapiListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="htmlapiParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery([NotNull] htmlapiParser.QueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="htmlapiParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery([NotNull] htmlapiParser.QueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="htmlapiParser.singleQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleQuery([NotNull] htmlapiParser.SingleQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="htmlapiParser.singleQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleQuery([NotNull] htmlapiParser.SingleQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="htmlapiParser.columnIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumnIdentifier([NotNull] htmlapiParser.ColumnIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="htmlapiParser.columnIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumnIdentifier([NotNull] htmlapiParser.ColumnIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="htmlapiParser.whereFilter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhereFilter([NotNull] htmlapiParser.WhereFilterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="htmlapiParser.whereFilter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhereFilter([NotNull] htmlapiParser.WhereFilterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="htmlapiParser.whereBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhereBody([NotNull] htmlapiParser.WhereBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="htmlapiParser.whereBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhereBody([NotNull] htmlapiParser.WhereBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="htmlapiParser.sortFilter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSortFilter([NotNull] htmlapiParser.SortFilterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="htmlapiParser.sortFilter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSortFilter([NotNull] htmlapiParser.SortFilterContext context);
}
